- name: "Installation de Docker et des dépendances"
  hosts: prod
  become: yes
  tasks:
    - name: "Installation de epel-release"
      yum:
        name: epel-release
        state: present
    - name: "Installation de Docker"
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3
          - docker
        state: present
    - name: "Démarrage du service Docker"
      service:
        name: docker
        state: started
        enabled: yes
    - name: "download pip script"
      get_url:
        url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
        dest: /tmp/get-pip.py
    - name: "Install python-pip"
      command: python3 /tmp/get-pip.py
    - name: "Install docker python"
      pip:
        name: docker
        executable: /usr/local/bin/pip3
